services:

  postgres:

    image: postgres:14
    environment:

      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom_pass
      POSTGRES_DB: ecom_agents

    ports:

      - "5432:5432"

    volumes:

      - pgdata:/var/lib/postgresql/data

  app:

    build:

      context: ..
      dockerfile: docker/Dockerfile

    depends_on:

      - postgres
    environment:

      - PERPLEXITY_KEY=${PERPLEXITY_KEY}
      - DB_URL=${DB_URL}

    volumes:
      - ..:/app

volumes:

  pgdata:
